//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int C_Id { get; set; }
        public string CompanyName { get; set; }
        public string DealerName { get; set; }
        public string Address { get; set; }
        public long Mobile { get; set; }
    }
}
