//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockIn
    {
        public int I_Id { get; set; }
        public string I_Name { get; set; }
        public string I_Description { get; set; }
        public int I_Quantity { get; set; }
        public int I_Price { get; set; }
        public int I_CompanyId { get; set; }
        public System.DateTime I_ExpiryDate { get; set; }
        public System.DateTime I_CreatedDate { get; set; }
        public string I_CreatedBy { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
